site_name: Kindle highlights & notes
site_url: https://josh-wong.github.io/kindle-highlights-notes/

# Add repo details in the top right-hand corner
repo_name: josh-wong/kindle-highlights-notes
repo_url: https://github.com/josh-wong/kindle-highlights-notes/
edit_uri: blob/main/docs

plugins:
  - search
  #- techdocs-core
  - git-revision-date-localized:
      type: date
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  - git-committers:
      repository: josh-wong/kindle-highlights-notes
      branch: main

markdown_extensions:
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add support for Material for MkDocs admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  # Add favicon to browser tab
  favicon: assets/images/favicon.png
  # Add logo to docs pages
  logo: assets/images/mkdocs_kindle.png
  icon:
    # Add icon to show repository information and link
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: light blue
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: light blue
      accent: blue
  features:
    # Add custom search functions
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

#nav:
#  - Overview: 'index.md'
#  - Getting started: '01_getting-started.md'
#  - Installing the Zune software: '02_installing-the-zune-software.md'
#  - Connecting to the Zune software: '03_connecting-with-the-zune-software.md'
#  - Adding apps and games (Zune HD only): '04_adding-apps-and-games.md'
#  - Conclusion: '05_conclusion.md'
#  - References: '06_references.md'
#  - Contributions: '07_contributions.md'